// InvestED educational text for concepts added by the concept registry.
// Plain language, no numbers, no market facts. Shown through the same concept answer path as the rest.
export interface ExtraConcept { patterns: RegExp[]; heLabel: string; enLabel: string; he: string; en: string; }

export const EXTRA_CONCEPTS: ExtraConcept[] = [
  { patterns: [/sharpe/i, /שארפ/, /risk[- ]adjusted\s+return/i, /תשואה\s+מתואמת\s+סיכון/], heLabel: "יחס שארפ", enLabel: "Sharpe Ratio",
    he: "יחס שארפ בודק כמה תשואה קיבלתם על כל יחידת סיכון שלקחתם. ככל שהיחס גבוה יותר, ההשקעה נתנה יותר תשואה ביחס לתנודתיות שלה. הוא טוב להשוואה בין שתי השקעות, אבל הוא מבוסס על העבר ולא מבטיח את העתיד.",
    en: "The Sharpe ratio checks how much return you got for each unit of risk you took. A higher ratio means the investment paid more for its ups and downs. It is good for comparing two investments, but it looks at the past and does not promise the future." },
  { patterns: [/sortino/i, /סורטינו/], heLabel: "יחס סורטינו", enLabel: "Sortino Ratio",
    he: "יחס סורטינו דומה ליחס שארפ, אבל סופר רק את התנודות כלפי מטה, כלומר ההפסדים. כך תנודות שמחות, כמו עליות חדות, לא נחשבות כסיכון.",
    en: "The Sortino ratio is like the Sharpe ratio, but it counts only the moves down, the losses. So happy surprises, like sharp rises, are not treated as risk." },
  { patterns: [/\balpha\b/i, /אלפא/], heLabel: "אלפא", enLabel: "Alpha",
    he: "אלפא מודד כמה תשואה קרן או מנהל תיק הוסיפו מעבר למה שהמדד והסיכון מסבירים. אלפא חיובית אומרת שהוא ניצח את ההשוואה. קשה לשמור עליה לאורך זמן.",
    en: "Alpha measures how much extra return a fund or manager added beyond what the market and the risk taken explain. A positive alpha means it beat the comparison. It is hard to keep for a long time." },
  { patterns: [/correlation/i, /קורלציה/, /(?<![א-ת])מתאם(?![א-ת])/], heLabel: "מתאם", enLabel: "Correlation",
    he: "מתאם (קורלציה) מראה עד כמה שני נכסים זזים יחד. אם הם זזים באותו כיוון, המתאם גבוה. נכסים עם מתאם נמוך עוזרים לפזר סיכון, כי כשאחד יורד השני לא בהכרח יורד.",
    en: "Correlation shows how much two assets move together. If they move in the same direction, correlation is high. Assets with low correlation help spread risk, because when one falls the other does not have to." },
  { patterns: [/benchmark/i, /מדד\s+ייחוס/, /מדד\s+השוואה/], heLabel: "מדד ייחוס", enLabel: "Benchmark",
    he: "מדד ייחוס הוא מדד שמשווים אליו את ההשקעה שלכם, למשל S&P 500 לקרן מניות אמריקאית. הוא עוזר להבין אם התשואה הייתה טובה או רק שהשוק כולו עלה.",
    en: "A benchmark is the index you compare your investment with, for example the S&P 500 for a US stock fund. It helps you see if the result was good or if the whole market simply went up." },
  { patterns: [/portfolio\s+optimi[sz]ation/i, /efficient\s+frontier/i, /אופטימיזציית\s+תיק/, /הגבול\s+היעיל/], heLabel: "אופטימיזציית תיק", enLabel: "Portfolio Optimization",
    he: "אופטימיזציית תיק היא חיפוש אחרי תמהיל נכסים שנותן את התשואה הטובה ביותר לרמת סיכון נתונה. היא נשענת על הערכות מהעבר, ולכן התוצאה היא כלי חשיבה ולא הבטחה.",
    en: "Portfolio optimization is the search for the mix of assets that gives the best return for a given level of risk. It relies on estimates from the past, so the result is a thinking tool, not a promise." },
  { patterns: [/\bcapm\b/i, /capital\s+asset\s+pricing/i], heLabel: "מודל CAPM", enLabel: "CAPM",
    he: "CAPM הוא מודל שאומר איזו תשואה כדאי לצפות לה מנכס לפי הסיכון שלו ביחס לשוק (הבטא שלו). נכס מסוכן יותר אמור לתת תשואה צפויה גבוהה יותר. זה מודל פשוט, והמציאות מורכבת ממנו.",
    en: "CAPM is a model that says what return to expect from an asset given its risk compared with the market (its beta). A riskier asset should offer a higher expected return. It is a simple model, and real life is more complex." },
  { patterns: [/valuation/i, /הערכת\s+שווי/, /שווי\s+הוגן/, /intrinsic\s+value/i], heLabel: "הערכת שווי", enLabel: "Valuation",
    he: "הערכת שווי היא ניסיון להבין כמה חברה שווה, ולהשוות את זה למחיר שלה בשוק. משתמשים בכמה שיטות, כמו מכפילים ותזרים מהוון. כל שיטה נשענת על הנחות, לכן שני אנשים יכולים להגיע למספרים שונים.",
    en: "Valuation is the attempt to work out what a company is worth and compare it with its market price. People use several methods, such as multiples and discounted cash flow. Each one rests on assumptions, so two people can reach different numbers." },
  { patterns: [/\bdcf\b/i, /discounted\s+cash\s*flow/i, /תזרים\s+מהוון/, /היוון\s+תזרימים/], heLabel: "תזרים מהוון (DCF)", enLabel: "DCF",
    he: "DCF מעריך חברה לפי הכסף שהיא צפויה להרוויח בעתיד, אחרי שמחשבים כמה הכסף הזה שווה היום. כסף שמגיע בעוד שנים שווה פחות מכסף היום. התוצאה רגישה מאוד להנחות, ולכן היא הערכה ולא עובדה.",
    en: "DCF values a company by the money it is expected to earn in the future, after working out what that money is worth today. Money that arrives years from now is worth less than money today. The result is very sensitive to the assumptions, so it is an estimate, not a fact." },
  { patterns: [/ev\s*\/\s*ebitda/i, /enterprise\s+value/i, /שווי\s+מפעל/], heLabel: "מכפיל EV/EBITDA", enLabel: "EV/EBITDA",
    he: "EV/EBITDA משווה את שווי החברה כולה, כולל החובות שלה, לרווח התפעולי שלה לפני כמה הוצאות חשבונאיות. הוא שימושי להשוואה בין חברות עם מבנה חובות שונה.",
    en: "EV/EBITDA compares the value of the whole company, including its debt, with its operating profit before some accounting costs. It is useful for comparing companies that carry different amounts of debt." },
  { patterns: [/discount\s+rate/i, /שיעור\s+היוון/, /שיעור\s+ניכיון/], heLabel: "שיעור היוון", enLabel: "Discount Rate",
    he: "שיעור היוון הוא הריבית שבעזרתה מחשבים כמה כסף עתידי שווה היום. ככל שהוא גבוה יותר, כסף עתידי שווה פחות היום. הוא משקף את הסיכון ואת התשואה שהייתם דורשים.",
    en: "The discount rate is the rate used to work out what future money is worth today. The higher it is, the less future money is worth today. It reflects the risk and the return you would demand." },
  { patterns: [/\bduration\b/i, /מח["״]?מ/], heLabel: "מח״מ (Duration)", enLabel: "Duration",
    he: "מח״מ מראה עד כמה מחיר אג״ח רגיש לשינוי בריבית. ככל שהמח״מ ארוך יותר, המחיר זז יותר כשהריבית משתנה. כשהריבית עולה, מחירי אג״ח יורדים, וההפך.",
    en: "Duration shows how sensitive a bond's price is to a change in interest rates. The longer the duration, the more the price moves when rates change. When rates rise, bond prices fall, and the other way round." },
  { patterns: [/\bytm\b/i, /yield\s+to\s+maturity/i, /תשואה\s+לפדיון/], heLabel: "תשואה לפדיון", enLabel: "Yield",
    he: "תשואה לפדיון היא התשואה השנתית שתקבלו מאג״ח אם תחזיקו אותה עד הסוף ולא יהיה כשל. היא כוללת את הריבית שהאג״ח משלמת ואת ההפרש בין מחיר הקנייה לסכום שמחזירים.",
    en: "Yield to maturity is the yearly return you would get from a bond if you hold it to the end and nothing goes wrong. It includes the interest the bond pays and the gap between the price you paid and the amount repaid." },
  { patterns: [/\baml\b/i, /anti[- ]money\s+laundering/i, /הלבנת\s+הון/], heLabel: "איסור הלבנת הון", enLabel: "AML",
    he: "איסור הלבנת הון (AML) הוא מערך כללים שמונע הסתרה של כסף שמקורו בפשע. גופים פיננסיים בודקים מי הלקוח ומאיפה הכסף, ומדווחים על פעולות חשודות.",
    en: "Anti-money laundering (AML) is a set of rules that stops money from crime being hidden. Financial firms check who the customer is and where the money comes from, and report suspicious activity." },
  { patterns: [/\bkyc\b/i, /know\s+your\s+customer/i, /הכר\s+את\s+הלקוח/], heLabel: "הכר את הלקוח", enLabel: "KYC",
    he: "KYC, הכר את הלקוח, הוא התהליך שבו גוף פיננסי מוודא מי אתם: זיהוי, כתובת, מקור הכסף ומטרת ההשקעה. הוא חלק מהמאבק בהלבנת הון, ומסייע גם להתאים מוצרים ללקוח.",
    en: "KYC, know your customer, is the process where a financial firm checks who you are: identity, address, source of money and goal of the investment. It is part of fighting money laundering and also helps match products to the client." },
  { patterns: [/suitability/i, /התאמה\s+ללקוח/, /התאמת\s+השקעה/], heLabel: "התאמה ללקוח", enLabel: "Suitability",
    he: "התאמה ללקוח אומרת שמוצר השקעה צריך להתאים למצב של האדם: המטרה שלו, הידע שלו, הזמן שיש לו וכמה סיכון הוא יכול לשאת. ייעוץ מקצועי חייב לבדוק את זה לפני המלצה.",
    en: "Suitability means an investment product should fit the person: their goal, their knowledge, their time and how much risk they can bear. Professional advice has to check this before it recommends anything." },
  { patterns: [/conflicts?\s+of\s+interest/i, /ניגוד\s+עניינים/], heLabel: "ניגוד עניינים", enLabel: "Conflict of Interest",
    he: "ניגוד עניינים קורה כשלמי שמייעץ לכם יש אינטרס אחר משלכם, למשל עמלה על מוצר מסוים. הכלל הוא לגלות את זה ולהעדיף את טובת הלקוח.",
    en: "A conflict of interest happens when the person advising you has a different interest than yours, for example a fee on a certain product. The rule is to disclose it and put the client first." },
  { patterns: [/market\s+abuse/i, /insider\s+trading/i, /מסחר\s+פנים/, /מניפולציה\s+בשוק/, /ניצול\s+לרעה\s+של\s+שוק/], heLabel: "ניצול לרעה של שוק", enLabel: "Market Abuse",
    he: "ניצול לרעה של שוק הוא התנהגות לא הוגנת שמעוותת את המסחר, כמו שימוש במידע פנים שלא פורסם או מניפולציה במחיר. זה אסור בחוק, והמטרה היא להגן על ההגינות של השוק.",
    en: "Market abuse is unfair behavior that distorts trading, such as using inside information that is not public or manipulating a price. It is against the law, and the aim is to keep the market fair." },
  { patterns: [/compliance/i, /regtech/i, /ציות\s+ואכיפה/, /(?<![א-ת])ציות(?![א-ת])/], heLabel: "ציות", enLabel: "Compliance",
    he: "ציות הוא התפקיד בגוף פיננסי שדואג שהוא עובד לפי החוק והנהלים: רגולציה, אתיקה ושמירה על הלקוחות. גם מי שלא עובד בתחום צריך להכיר את העקרונות.",
    en: "Compliance is the function in a financial firm that makes sure it follows the law and its own rules: regulation, ethics and protecting clients. Even people outside the field should know the basics." },
  { patterns: [/fundamental\s+analysis/i, /ניתוח\s+פונדמנטלי/, /ניתוח\s+בסיסי/], heLabel: "ניתוח פונדמנטלי", enLabel: "Fundamental Analysis",
    he: "ניתוח פונדמנטלי בוחן את העסק עצמו: ההכנסות, הרווחים, החובות והצמיחה, כדי להבין כמה החברה שווה באמת. הוא מנסה לענות אם המחיר גבוה או נמוך ביחס לשווי.",
    en: "Fundamental analysis looks at the business itself: revenue, profit, debt and growth, to understand what the company is really worth. It tries to answer whether the price is high or low compared with the value." },
  { patterns: [/technical\s+analysis/i, /ניתוח\s+טכני/], heLabel: "ניתוח טכני", enLabel: "Technical Analysis",
    he: "ניתוח טכני בוחן גרפי מחירים וכמויות מסחר ומחפש דפוסים, כמו מגמות ורמות תמיכה. הוא לא בוחן את העסק עצמו. הרבה אנשים משתמשים בו לתזמון, ואין לו הוכחה שהוא מנבא את העתיד.",
    en: "Technical analysis looks at price charts and trading volume and searches for patterns, like trends and support levels. It does not study the business itself. Many people use it for timing, and there is no proof it predicts the future." },
  { patterns: [/financial\s+statements?/i, /balance\s+sheet/i, /income\s+statement/i, /דוחות?\s+כספיים/, /מאזן/, /דוח\s+רווח\s+והפסד/], heLabel: "דוחות כספיים", enLabel: "Financial Statements",
    he: "הדוחות הכספיים של חברה הם שלושה מסמכים. דוח רווח והפסד מראה כמה היא הרוויחה. מאזן מראה מה יש לה ומה היא חייבת. דוח תזרים מזומנים מראה לאן הכסף נכנס ויצא. הם מקור הנתונים העיקרי להערכת חברה.",
    en: "A company's financial statements are three documents. The income statement shows how much it earned. The balance sheet shows what it owns and owes. The cash flow statement shows where cash came in and went out. They are the main source of data for judging a company." },
  { patterns: [/portfolio\s+manager/i, /מנהל(?:ת)?\s+תיק/], heLabel: "מנהל תיק", enLabel: "Portfolio Manager",
    he: "מנהל תיק מחליט איך לחלק כסף בין נכסים, מה לקנות ומה למכור, לפי מטרה ורמת סיכון שהוגדרו מראש. הוא נמדד לפי תוצאות מול מדד ייחוס. אפשר לתרגל את התפקיד במעבדת הקריירה.",
    en: "A portfolio manager decides how to split money between assets, what to buy and what to sell, based on a goal and level of risk set in advance. They are judged against a benchmark. You can practice the role in the Career Lab." },
  { patterns: [/investment\s+analyst/i, /equity\s+research/i, /אנליסט\s+השקעות/, /מחקר\s+מניות/], heLabel: "אנליסט השקעות", enLabel: "Investment Analyst",
    he: "אנליסט השקעות חוקר חברות ושווקים, בונה הערכות שווי וכותב המלצות למי שמחליט על ההשקעה. הוא קורא דוחות, בונה מודלים ומסביר את ההנחות שלו. אפשר לתרגל את התפקיד במעבדת הקריירה.",
    en: "An investment analyst researches companies and markets, builds valuations and writes recommendations for the people who decide on the investment. They read reports, build models and explain their assumptions. You can practice the role in the Career Lab." },
  { patterns: [/\binsurance\b/i, /(?<![א-ת])ביטוח(?:ים)?(?![א-ת])/], heLabel: "ביטוח", enLabel: "Insurance",
    he: "ביטוח הוא הסכם: אתם משלמים סכום קבוע, וחברת הביטוח מתחייבת לשלם אם קורה אירוע מסוים, כמו תאונה, מחלה או נזק לבית. הרעיון הוא להעביר סיכון גדול שלא הייתם יכולים לשאת לבד לחברה שמחלקת אותו בין הרבה לקוחות. ביטוח לא מרוויח כסף בשבילכם, הוא מגן עליכם מהפסד גדול.",
    en: "Insurance is an agreement: you pay a fixed amount, and the insurer promises to pay if a named event happens, such as an accident, an illness or damage to your home. The idea is to move a big risk you could not carry alone to a company that spreads it across many customers. Insurance does not earn money for you, it protects you from a large loss." },
  { patterns: [/\bpremiums?\b/i, /פרמי(?:ה|ות)/], heLabel: "פרמיה", enLabel: "Premium",
    he: "פרמיה היא הסכום שמשלמים לחברת הביטוח עבור הכיסוי, בדרך כלל כל חודש או פעם בשנה. היא תלויה בסוג הכיסוי, בגורמי הסיכון שלכם ובגובה ההשתתפות העצמית. הפרמיה הזולה ביותר היא לא תמיד הכי משתלמת, כי כדאי לבדוק גם מה בדיוק מכוסה.",
    en: "A premium is the amount you pay the insurer for the cover, usually every month or once a year. It depends on the type of cover, your risk factors and the size of the deductible. The cheapest premium is not always the best deal, because you should also check what exactly is covered." },
  { patterns: [/deductibles?/i, /השתתפות\s+עצמית/], heLabel: "השתתפות עצמית", enLabel: "Deductible",
    he: "השתתפות עצמית היא החלק מהנזק שאתם משלמים מהכיס לפני שהביטוח משלם את השאר. השתתפות עצמית גבוהה בדרך כלל מקטינה את הפרמיה, אבל אומרת שבמקרה נזק תשלמו יותר. בחרו סכום שתוכלו לשלם בלי להיכנס ללחץ.",
    en: "A deductible is the part of a loss you pay yourself before the insurance pays the rest. A higher deductible usually lowers the premium, but it means you pay more when something goes wrong. Pick an amount you could pay without stress." },
  { patterns: [/life\s+insurance/i, /ביטוח\s+חיים/], heLabel: "ביטוח חיים", enLabel: "Life insurance",
    he: "ביטוח חיים משלם סכום למי שתבחרו, למשל בן או בת זוג וילדים, אם אתם נפטרים. הוא חשוב בעיקר למי שיש לו תלויים או חובות, כמו משכנתא. יש ביטוח שמיועד רק לכיסוי למקרה מוות, ויש שמשלבים בו חיסכון. כדאי להשוות בין החלופות ולקרוא מה לא מכוסה.",
    en: "Life insurance pays an amount to the people you choose, such as a partner and children, if you die. It matters most for people who have dependants or debts, like a mortgage. Some policies cover only death, and some mix in savings. Compare the options and read what is not covered." },
  { patterns: [/(?:health|medical)\s+insurance/i, /ביטוח\s+(?:בריאות|רפואי)/], heLabel: "ביטוח בריאות", enLabel: "Health insurance",
    he: "ביטוח בריאות מכסה חלק מהוצאות הטיפול הרפואי, למשל ניתוחים, תרופות או בדיקות שלא נכללות בשירות הציבורי. כדאי לבדוק מה כבר יש לכם דרך קופת החולים או העבודה כדי לא לשלם פעמיים על אותו כיסוי.",
    en: "Health insurance covers part of your medical costs, for example surgery, medicines or tests that the public system does not include. Check what you already have through your health fund or your job so you do not pay twice for the same cover." },
  { patterns: [/(?:car|auto|vehicle)\s+insurance/i, /ביטוח\s+רכב/], heLabel: "ביטוח רכב", enLabel: "Car insurance",
    he: "ביטוח רכב מכסה נזק לרכב שלכם, לרכב של אחרים ולפעמים לנוסעים. ביטוח חובה מכסה נזק גוף לאחרים, וביטוח מקיף מוסיף כיסוי לרכב עצמו. מחיר הביטוח תלוי בגיל הנהג, בניסיון, ברכב ובהשתתפות העצמית.",
    en: "Car insurance covers damage to your car, to other people's cars and sometimes to passengers. Compulsory cover handles injury to others, and comprehensive cover adds protection for your own car. The price depends on the driver's age and experience, the car and the deductible." },
  { patterns: [/credit\s+(?:score|history|report)/i, /(?:דירוג|ציון)\s+אשראי/], heLabel: "דירוג אשראי", enLabel: "Credit score",
    he: "דירוג אשראי הוא ציון שמסכם עד כמה אתם אמינים בהחזר חובות. הוא נשען על היסטוריית תשלומים, גובה החובות, כמה זמן יש לכם אשראי ובקשות חדשות להלוואות. תשלום בזמן ושימוש מתון במסגרת האשראי משפרים אותו, ואיחורים פוגעים בו.",
    en: "A credit score is a rating of how reliable you are at paying back debt. It builds on your payment history, how much debt you hold, how long you have had credit and new loan requests. Paying on time and using only part of your credit limit helps it, and late payments hurt it." },
  { patterns: [/\bapr\b/i, /annual\s+percentage\s+rate/i, /ריבית\s+(?:שנתית\s+)?אפקטיבית/], heLabel: "ריבית שנתית אפקטיבית", enLabel: "APR (annual percentage rate)",
    he: "ריבית שנתית אפקטיבית (APR) מראה את העלות השנתית האמיתית של הלוואה, כולל עמלות, ולא רק את הריבית הנקובה. כשמשווים הלוואות, השוו את הריבית האפקטיבית ולא את הריבית שבפרסומת.",
    en: "The annual percentage rate (APR) shows the real yearly cost of a loan, including fees, not only the stated interest. When you compare loans, compare the APR, not the rate in the advert." },
  { patterns: [/(?:fixed|variable|floating)\s+(?:interest\s+)?rate/i, /ריבית\s+(?:קבועה|משתנה)/], heLabel: "ריבית קבועה מול משתנה", enLabel: "Fixed vs variable rate",
    he: "בריבית קבועה אתם יודעים מראש כמה תשלמו, כי היא לא משתנה לאורך ההלוואה. בריבית משתנה התשלום עולה ויורד לפי הריבית במשק. קבועה נותנת ודאות, ומשתנה יכולה להתחיל זולה יותר אבל מסוכנת יותר אם הריבית עולה.",
    en: "With a fixed rate you know in advance what you will pay, because it does not change during the loan. With a variable rate the payment moves with interest rates in the economy. Fixed gives certainty, and variable can start cheaper but is riskier if rates rise." },
  { patterns: [/refinanc/i, /מחזור\s+(?:משכנתא|הלוואה|הלוואות)/], heLabel: "מחזור הלוואה", enLabel: "Refinancing",
    he: "מחזור הוא לקיחת הלוואה חדשה כדי לסגור הלוואה קיימת, בדרך כלל כדי להוזיל ריבית או לשנות את תנאי ההחזר. לפני שמחזרים, בדקו קנסות פירעון מוקדם ועמלות, כי הם יכולים לבלוע את החיסכון.",
    en: "Refinancing means taking a new loan to pay off an existing one, usually to lower the interest or change the repayment terms. Before you refinance, check early-repayment penalties and fees, because they can eat the saving." },
  { patterns: [/\bbudget(?:ing)?\b/i, /תקציב/], heLabel: "תקציב", enLabel: "Budget",
    he: "תקציב הוא תוכנית לכסף שלכם: כמה נכנס, כמה יוצא ומה נשאר. הוא מראה לאן הכסף הולך ומאפשר להחליט מראש כמה לחסוך. הצעד הראשון הוא לרשום הוצאות קבועות ומשתנות במשך חודש, ורק אחר כך לקבוע יעדים.",
    en: "A budget is a plan for your money: what comes in, what goes out and what is left. It shows where the money goes and lets you decide in advance how much to save. The first step is to write down fixed and changing costs for a month, and only then set targets." },
  { patterns: [/net\s+worth/i, /(?:שווי|הון)\s+נטו/], heLabel: "שווי נטו", enLabel: "Net worth",
    he: "שווי נטו הוא מה שיש לכם פחות מה שאתם חייבים. מחברים את הנכסים, כמו חיסכון, השקעות ונדל\"ן, ומפחיתים את החובות. כדאי לבדוק אותו פעם או פעמיים בשנה: אם הוא גדל, אתם בכיוון הנכון.",
    en: "Net worth is what you own minus what you owe. Add up your assets, such as savings, investments and property, then subtract your debts. Track it once or twice a year: if it grows, you are moving in the right direction." },
  { patterns: [/credit\s+cards?/i, /כרטיס(?:י)?\s+אשראי/], heLabel: "כרטיס אשראי", enLabel: "Credit card",
    he: "כרטיס אשראי מאפשר לקנות עכשיו ולשלם לבנק אחר כך. אם משלמים את כל החיוב בזמן, בדרך כלל אין ריבית. אם משאירים יתרה, הריבית לרוב גבוהה והקנייה נעשית יקרה יותר. השתמשו בו רק לסכומים שתוכלו להחזיר החודש.",
    en: "A credit card lets you spend now and pay the bank later. If you pay the full bill on time, you usually pay no interest. If you carry a balance, the interest is often high, so the cost of what you bought grows. Use it only for amounts you can repay this month." },
  { patterns: [/overdraft/i, /משיכת\s+יתר/, /מינוס\s+בחשבון/], heLabel: "משיכת יתר", enLabel: "Overdraft",
    he: "משיכת יתר היא הוצאה של יותר ממה שיש בחשבון, עד מסגרת שהבנק מאשר. זו הלוואה, והריבית בדרך כלל גבוהה יותר מהלוואה רגילה. כדאי להשתמש בה לפערים קצרים ולא כדרך חיים.",
    en: "An overdraft means spending more than you have in your bank account, up to a limit the bank allows. It is a loan, and the interest is usually higher than on a regular loan. Use it for short gaps, not as a way of living." },
  { patterns: [/stop[\s-]?loss/i, /סטופ[\s-]?לוס/], heLabel: "פקודת סטופ לוס", enLabel: "Stop-loss",
    he: "סטופ לוס היא פקודה שמוכרת פוזיציה אוטומטית אם המחיר יורד לרמה שקבעתם. היא מגבילה הפסד, אבל אינה ערובה: בירידה מהירה המכירה יכולה להתבצע במחיר נמוך מהרמה שלכם, וירידה קצרה יכולה להפעיל מכירה שלא רציתם.",
    en: "A stop-loss is an order that sells a position automatically if the price falls to a level you set. It limits a loss, but it is not a guarantee: in a fast drop the sale can happen at a lower price than your level, and a short dip can trigger a sale you did not want." },
  { patterns: [/recession/i, /(?<![א-ת])מיתון(?![א-ת])/], heLabel: "מיתון", enLabel: "Recession",
    he: "מיתון הוא תקופה שבה המשק מתכווץ: התוצר, התעסוקה והצריכה יורדים במשך כמה חודשים. חברות מרוויחות פחות ומחירי מניות לרוב יורדים, אבל השווקים גם נוטים להתאושש אחר כך. מיתון הוא סיבה לבדוק את התוכנית ואת קרן החירום, לא סיבה להיבהל.",
    en: "A recession is a period when the economy shrinks: production, jobs and spending fall for several months. Companies earn less and stock prices often drop, but markets also tend to recover afterwards. A recession is a reason to check your plan and your emergency fund, not to panic." },
  { patterns: [/\bgdp\b/i, /gross\s+domestic\s+product/i, /תוצר\s+מקומי/, /תמ\"ג/], heLabel: "תוצר מקומי גולמי", enLabel: "GDP",
    he: "תמ\"ג, תוצר מקומי גולמי, הוא הערך הכולל של הסחורות והשירותים שמדינה מייצרת בתקופה, בדרך כלל שנה. כשהוא גדל, המשק מתרחב. כדאי להשוות צמיחה אחרי אינפלציה, כי עליית מחירים יכולה לנפח את התמ\"ג בלי שייוצר יותר.",
    en: "GDP, gross domestic product, is the total value of goods and services a country produces in a period, usually a year. When it grows, the economy is expanding. Compare growth after inflation, because prices rising can make GDP look bigger without more being produced." },
  { patterns: [/(?:investment\s+)?scam/i, /\bfraud/i, /ponzi/i, /הונא(?:ה|ות)/, /פירמיד(?:ה|ת)/], heLabel: "הונאת השקעות", enLabel: "Investment scam",
    he: "סימני אזהרה להונאת השקעות: הבטחה לתשואה גבוהה ומובטחת בלי סיכון, לחץ להחליט מהר, אדם זר שפנה אליכם, תשלום בקריפטו או בשוברים, ומוכר בלי רישיון. אם זה נשמע טוב מדי, עצרו ובדקו את המוכר מול הרגולטור הפיננסי לפני שמעבירים כסף.",
    en: "Warning signs of an investment scam: a promise of high guaranteed returns with no risk, pressure to decide fast, a stranger who contacted you first, payment by crypto or gift cards, and an unlicensed seller. If it sounds too good to be true, stop and check the seller with the financial regulator before sending money." },
  { patterns: [/annuit/i, /קצבה/, /קצבת\s+פנסיה/], heLabel: "קצבה", enLabel: "Annuity",
    he: "קצבה היא תשלום קבוע, בדרך כלל חודשי, שמקבלים לתקופה מוגדרת או לכל החיים. בפנסיה, הסכום שנחסך הופך לתשלום חודשי אחרי הפרישה. גובה התשלום תלוי בסכום שנחסך ובתנאים.",
    en: "An annuity is a regular payment, usually monthly, that you receive for a set period or for life. In pensions, the saved amount is turned into a monthly payment after retirement. The size of the payment depends on how much was saved and on the terms." },
];
