// InvestED educational text for concepts added by the concept registry.
// Plain language, no numbers, no market facts. Shown through the same concept answer path as the rest.
export interface ExtraConcept { patterns: RegExp[]; heLabel: string; enLabel: string; he: string; en: string; }

export const EXTRA_CONCEPTS: ExtraConcept[] = [
  { patterns: [/sharpe/i, /שארפ/, /risk[- ]adjusted\s+return/i, /תשואה\s+מתואמת\s+סיכון/], heLabel: "יחס שארפ", enLabel: "Sharpe Ratio",
    he: "יחס שארפ בודק כמה תשואה קיבלתם על כל יחידת סיכון שלקחתם. ככל שהיחס גבוה יותר, ההשקעה נתנה יותר תשואה ביחס לתנודתיות שלה. הוא טוב להשוואה בין שתי השקעות, אבל הוא מבוסס על העבר ולא מבטיח את העתיד.",
    en: "The Sharpe ratio checks how much return you got for each unit of risk you took. A higher ratio means the investment paid more for its ups and downs. It is good for comparing two investments, but it looks at the past and does not promise the future." },
  { patterns: [/sortino/i, /סורטינו/], heLabel: "יחס סורטינו", enLabel: "Sortino Ratio",
    he: "יחס סורטינו דומה ליחס שארפ, אבל סופר רק את התנודות כלפי מטה, כלומר ההפסדים. כך תנודות שמחות, כמו עליות חדות, לא נחשבות כסיכון.",
    en: "The Sortino ratio is like the Sharpe ratio, but it counts only the moves down, the losses. So happy surprises, like sharp rises, are not treated as risk." },
  { patterns: [/\balpha\b/i, /אלפא/], heLabel: "אלפא", enLabel: "Alpha",
    he: "אלפא מודד כמה תשואה קרן או מנהל תיק הוסיפו מעבר למה שהמדד והסיכון מסבירים. אלפא חיובית אומרת שהוא ניצח את ההשוואה. קשה לשמור עליה לאורך זמן.",
    en: "Alpha measures how much extra return a fund or manager added beyond what the market and the risk taken explain. A positive alpha means it beat the comparison. It is hard to keep for a long time." },
  { patterns: [/correlation/i, /קורלציה/, /(?<![א-ת])מתאם(?![א-ת])/], heLabel: "מתאם", enLabel: "Correlation",
    he: "מתאם (קורלציה) מראה עד כמה שני נכסים זזים יחד. אם הם זזים באותו כיוון, המתאם גבוה. נכסים עם מתאם נמוך עוזרים לפזר סיכון, כי כשאחד יורד השני לא בהכרח יורד.",
    en: "Correlation shows how much two assets move together. If they move in the same direction, correlation is high. Assets with low correlation help spread risk, because when one falls the other does not have to." },
  { patterns: [/benchmark/i, /מדד\s+ייחוס/, /מדד\s+השוואה/], heLabel: "מדד ייחוס", enLabel: "Benchmark",
    he: "מדד ייחוס הוא מדד שמשווים אליו את ההשקעה שלכם, למשל S&P 500 לקרן מניות אמריקאית. הוא עוזר להבין אם התשואה הייתה טובה או רק שהשוק כולו עלה.",
    en: "A benchmark is the index you compare your investment with, for example the S&P 500 for a US stock fund. It helps you see if the result was good or if the whole market simply went up." },
  { patterns: [/portfolio\s+optimi[sz]ation/i, /efficient\s+frontier/i, /אופטימיזציית\s+תיק/, /הגבול\s+היעיל/], heLabel: "אופטימיזציית תיק", enLabel: "Portfolio Optimization",
    he: "אופטימיזציית תיק היא חיפוש אחרי תמהיל נכסים שנותן את התשואה הטובה ביותר לרמת סיכון נתונה. היא נשענת על הערכות מהעבר, ולכן התוצאה היא כלי חשיבה ולא הבטחה.",
    en: "Portfolio optimization is the search for the mix of assets that gives the best return for a given level of risk. It relies on estimates from the past, so the result is a thinking tool, not a promise." },
  { patterns: [/\bcapm\b/i, /capital\s+asset\s+pricing/i], heLabel: "מודל CAPM", enLabel: "CAPM",
    he: "CAPM הוא מודל שאומר איזו תשואה כדאי לצפות לה מנכס לפי הסיכון שלו ביחס לשוק (הבטא שלו). נכס מסוכן יותר אמור לתת תשואה צפויה גבוהה יותר. זה מודל פשוט, והמציאות מורכבת ממנו.",
    en: "CAPM is a model that says what return to expect from an asset given its risk compared with the market (its beta). A riskier asset should offer a higher expected return. It is a simple model, and real life is more complex." },
  { patterns: [/valuation/i, /הערכת\s+שווי/, /שווי\s+הוגן/, /intrinsic\s+value/i], heLabel: "הערכת שווי", enLabel: "Valuation",
    he: "הערכת שווי היא ניסיון להבין כמה חברה שווה, ולהשוות את זה למחיר שלה בשוק. משתמשים בכמה שיטות, כמו מכפילים ותזרים מהוון. כל שיטה נשענת על הנחות, לכן שני אנשים יכולים להגיע למספרים שונים.",
    en: "Valuation is the attempt to work out what a company is worth and compare it with its market price. People use several methods, such as multiples and discounted cash flow. Each one rests on assumptions, so two people can reach different numbers." },
  { patterns: [/\bdcf\b/i, /discounted\s+cash\s*flow/i, /תזרים\s+מהוון/, /היוון\s+תזרימים/], heLabel: "תזרים מהוון (DCF)", enLabel: "DCF",
    he: "DCF מעריך חברה לפי הכסף שהיא צפויה להרוויח בעתיד, אחרי שמחשבים כמה הכסף הזה שווה היום. כסף שמגיע בעוד שנים שווה פחות מכסף היום. התוצאה רגישה מאוד להנחות, ולכן היא הערכה ולא עובדה.",
    en: "DCF values a company by the money it is expected to earn in the future, after working out what that money is worth today. Money that arrives years from now is worth less than money today. The result is very sensitive to the assumptions, so it is an estimate, not a fact." },
  { patterns: [/ev\s*\/\s*ebitda/i, /enterprise\s+value/i, /שווי\s+מפעל/], heLabel: "מכפיל EV/EBITDA", enLabel: "EV/EBITDA",
    he: "EV/EBITDA משווה את שווי החברה כולה, כולל החובות שלה, לרווח התפעולי שלה לפני כמה הוצאות חשבונאיות. הוא שימושי להשוואה בין חברות עם מבנה חובות שונה.",
    en: "EV/EBITDA compares the value of the whole company, including its debt, with its operating profit before some accounting costs. It is useful for comparing companies that carry different amounts of debt." },
  { patterns: [/discount\s+rate/i, /שיעור\s+היוון/, /שיעור\s+ניכיון/], heLabel: "שיעור היוון", enLabel: "Discount Rate",
    he: "שיעור היוון הוא הריבית שבעזרתה מחשבים כמה כסף עתידי שווה היום. ככל שהוא גבוה יותר, כסף עתידי שווה פחות היום. הוא משקף את הסיכון ואת התשואה שהייתם דורשים.",
    en: "The discount rate is the rate used to work out what future money is worth today. The higher it is, the less future money is worth today. It reflects the risk and the return you would demand." },
  { patterns: [/\bduration\b/i, /מח["״]?מ/], heLabel: "מח״מ (Duration)", enLabel: "Duration",
    he: "מח״מ מראה עד כמה מחיר אג״ח רגיש לשינוי בריבית. ככל שהמח״מ ארוך יותר, המחיר זז יותר כשהריבית משתנה. כשהריבית עולה, מחירי אג״ח יורדים, וההפך.",
    en: "Duration shows how sensitive a bond's price is to a change in interest rates. The longer the duration, the more the price moves when rates change. When rates rise, bond prices fall, and the other way round." },
  { patterns: [/\bytm\b/i, /yield\s+to\s+maturity/i, /תשואה\s+לפדיון/], heLabel: "תשואה לפדיון", enLabel: "Yield",
    he: "תשואה לפדיון היא התשואה השנתית שתקבלו מאג״ח אם תחזיקו אותה עד הסוף ולא יהיה כשל. היא כוללת את הריבית שהאג״ח משלמת ואת ההפרש בין מחיר הקנייה לסכום שמחזירים.",
    en: "Yield to maturity is the yearly return you would get from a bond if you hold it to the end and nothing goes wrong. It includes the interest the bond pays and the gap between the price you paid and the amount repaid." },
  { patterns: [/\baml\b/i, /anti[- ]money\s+laundering/i, /הלבנת\s+הון/], heLabel: "איסור הלבנת הון", enLabel: "AML",
    he: "איסור הלבנת הון (AML) הוא מערך כללים שמונע הסתרה של כסף שמקורו בפשע. גופים פיננסיים בודקים מי הלקוח ומאיפה הכסף, ומדווחים על פעולות חשודות.",
    en: "Anti-money laundering (AML) is a set of rules that stops money from crime being hidden. Financial firms check who the customer is and where the money comes from, and report suspicious activity." },
  { patterns: [/\bkyc\b/i, /know\s+your\s+customer/i, /הכר\s+את\s+הלקוח/], heLabel: "הכר את הלקוח", enLabel: "KYC",
    he: "KYC, הכר את הלקוח, הוא התהליך שבו גוף פיננסי מוודא מי אתם: זיהוי, כתובת, מקור הכסף ומטרת ההשקעה. הוא חלק מהמאבק בהלבנת הון, ומסייע גם להתאים מוצרים ללקוח.",
    en: "KYC, know your customer, is the process where a financial firm checks who you are: identity, address, source of money and goal of the investment. It is part of fighting money laundering and also helps match products to the client." },
  { patterns: [/suitability/i, /התאמה\s+ללקוח/, /התאמת\s+השקעה/], heLabel: "התאמה ללקוח", enLabel: "Suitability",
    he: "התאמה ללקוח אומרת שמוצר השקעה צריך להתאים למצב של האדם: המטרה שלו, הידע שלו, הזמן שיש לו וכמה סיכון הוא יכול לשאת. ייעוץ מקצועי חייב לבדוק את זה לפני המלצה.",
    en: "Suitability means an investment product should fit the person: their goal, their knowledge, their time and how much risk they can bear. Professional advice has to check this before it recommends anything." },
  { patterns: [/conflicts?\s+of\s+interest/i, /ניגוד\s+עניינים/], heLabel: "ניגוד עניינים", enLabel: "Conflict of Interest",
    he: "ניגוד עניינים קורה כשלמי שמייעץ לכם יש אינטרס אחר משלכם, למשל עמלה על מוצר מסוים. הכלל הוא לגלות את זה ולהעדיף את טובת הלקוח.",
    en: "A conflict of interest happens when the person advising you has a different interest than yours, for example a fee on a certain product. The rule is to disclose it and put the client first." },
  { patterns: [/market\s+abuse/i, /insider\s+trading/i, /מסחר\s+פנים/, /מניפולציה\s+בשוק/, /ניצול\s+לרעה\s+של\s+שוק/], heLabel: "ניצול לרעה של שוק", enLabel: "Market Abuse",
    he: "ניצול לרעה של שוק הוא התנהגות לא הוגנת שמעוותת את המסחר, כמו שימוש במידע פנים שלא פורסם או מניפולציה במחיר. זה אסור בחוק, והמטרה היא להגן על ההגינות של השוק.",
    en: "Market abuse is unfair behavior that distorts trading, such as using inside information that is not public or manipulating a price. It is against the law, and the aim is to keep the market fair." },
  { patterns: [/compliance/i, /regtech/i, /ציות\s+ואכיפה/, /(?<![א-ת])ציות(?![א-ת])/], heLabel: "ציות", enLabel: "Compliance",
    he: "ציות הוא התפקיד בגוף פיננסי שדואג שהוא עובד לפי החוק והנהלים: רגולציה, אתיקה ושמירה על הלקוחות. גם מי שלא עובד בתחום צריך להכיר את העקרונות.",
    en: "Compliance is the function in a financial firm that makes sure it follows the law and its own rules: regulation, ethics and protecting clients. Even people outside the field should know the basics." },
  { patterns: [/fundamental\s+analysis/i, /ניתוח\s+פונדמנטלי/, /ניתוח\s+בסיסי/], heLabel: "ניתוח פונדמנטלי", enLabel: "Fundamental Analysis",
    he: "ניתוח פונדמנטלי בוחן את העסק עצמו: ההכנסות, הרווחים, החובות והצמיחה, כדי להבין כמה החברה שווה באמת. הוא מנסה לענות אם המחיר גבוה או נמוך ביחס לשווי.",
    en: "Fundamental analysis looks at the business itself: revenue, profit, debt and growth, to understand what the company is really worth. It tries to answer whether the price is high or low compared with the value." },
  { patterns: [/technical\s+analysis/i, /ניתוח\s+טכני/], heLabel: "ניתוח טכני", enLabel: "Technical Analysis",
    he: "ניתוח טכני בוחן גרפי מחירים וכמויות מסחר ומחפש דפוסים, כמו מגמות ורמות תמיכה. הוא לא בוחן את העסק עצמו. הרבה אנשים משתמשים בו לתזמון, ואין לו הוכחה שהוא מנבא את העתיד.",
    en: "Technical analysis looks at price charts and trading volume and searches for patterns, like trends and support levels. It does not study the business itself. Many people use it for timing, and there is no proof it predicts the future." },
  { patterns: [/financial\s+statements?/i, /balance\s+sheet/i, /income\s+statement/i, /דוחות?\s+כספיים/, /מאזן/, /דוח\s+רווח\s+והפסד/], heLabel: "דוחות כספיים", enLabel: "Financial Statements",
    he: "הדוחות הכספיים של חברה הם שלושה מסמכים: דוח רווח והפסד (כמה הרוויחה), מאזן (מה יש לה ומה היא חייבת) ודוח תזרים מזומנים (לאן הכסף נכנס ויצא). הם מקור הנתונים העיקרי להערכת חברה.",
    en: "A company's financial statements are three documents: the income statement (how much it earned), the balance sheet (what it owns and owes) and the cash flow statement (where cash came in and went out). They are the main source of data for judging a company." },
  { patterns: [/portfolio\s+manager/i, /מנהל(?:ת)?\s+תיק/], heLabel: "מנהל תיק", enLabel: "Portfolio Manager",
    he: "מנהל תיק מחליט איך לחלק כסף בין נכסים, מה לקנות ומה למכור, לפי מטרה ורמת סיכון שהוגדרו מראש. הוא נמדד לפי תוצאות מול מדד ייחוס. אפשר לתרגל את התפקיד במעבדת הקריירה.",
    en: "A portfolio manager decides how to split money between assets, what to buy and what to sell, based on a goal and level of risk set in advance. They are judged against a benchmark. You can practice the role in the Career Lab." },
  { patterns: [/investment\s+analyst/i, /equity\s+research/i, /אנליסט\s+השקעות/, /מחקר\s+מניות/], heLabel: "אנליסט השקעות", enLabel: "Investment Analyst",
    he: "אנליסט השקעות חוקר חברות ושווקים, בונה הערכות שווי וכותב המלצות למי שמחליט על ההשקעה. הוא קורא דוחות, בונה מודלים ומסביר את ההנחות שלו. אפשר לתרגל את התפקיד במעבדת הקריירה.",
    en: "An investment analyst researches companies and markets, builds valuations and writes recommendations for the people who decide on the investment. They read reports, build models and explain their assumptions. You can practice the role in the Career Lab." },
];
