import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {useLanguage} from "@/context/languageContext";
import {fetchMarketMovers,type MarketMoversResult} from "@/lib/marketMovers";
import {fetchMarketAssetBySymbol} from "@/lib/marketData";
import {researchCodeLabel} from "@/lib/research/researchLabels";
import {resolveAssetSymbol} from "@/lib/market/symbolResolution";
import type {MarketAsset} from "@/types";
import {Panel,ProvenanceBadge,StatusIndicator} from "@/components/ui/terminal";
import {ChatDataDesk} from "@/components/dashboard/ChatDataDesk";

export default function MarketsWorkspace(){
 const {language,t}=useLanguage();const he=language==="he";
 const [symbols,setSymbols]=useState<string[]>(()=>{try{const saved=JSON.parse(localStorage.getItem("invested-terminal-watchlist")??"null");return Array.isArray(saved)?saved.filter((s):s is string=>typeof s==="string").slice(0,20):["SPY","QQQ","NVDA"];}catch{return["SPY","QQQ","NVDA"];}});
 const [assets,setAssets]=useState<Record<string,MarketAsset|null>>({});const [input,setInput]=useState("");const [note,setNote]=useState("");const [movers,setMovers]=useState<MarketMoversResult|null>(null);const [failed,setFailed]=useState(false);const [refresh,setRefresh]=useState(0);
 useEffect(()=>{let active=true;setFailed(false);fetchMarketMovers().then(result=>{if(active)setMovers(result);}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};},[refresh]);
 useEffect(()=>{localStorage.setItem("invested-terminal-watchlist",JSON.stringify(symbols));let active=true;setAssets({});for(const symbol of symbols)void fetchMarketAssetBySymbol(symbol,"3mo",undefined,{allowSimulated:false}).then(asset=>{if(active)setAssets(current=>({...current,[symbol]:asset}));}).catch(()=>{if(active)setAssets(current=>({...current,[symbol]:null}));});return()=>{active=false;};},[symbols,refresh]);
 function add(){const match=resolveAssetSymbol(input);if(!match){setNote(he?"הסימול לא נמצא ברשימת הנכסים הנתמכים.":"Symbol not found in the supported asset list.");return;}if(symbols.length>=20){setNote(he?"ניתן לשמור עד 20 נכסים.":"You can save up to 20 assets.");return;}setSymbols(current=>current.includes(match.symbol)?current:[...current,match.symbol]);setInput("");setNote("");}
 return <div className="terminal-market-workspace"><div className="terminal-workspace-title"><div><span className="terminal-eyebrow">INVESTED / MARKETS</span><h1>{he?"שווקים ורשימת מעקב":"Markets & watchlist"}</h1></div><button className="terminal-control" onClick={()=>setRefresh(current=>current+1)}>{he?"רענון נתונים":"Refresh data"}</button></div>
 <Panel title={he?"רשימת המעקב שלי":"My watchlist"} actions={<ProvenanceBadge kind="data"/>}><form className="terminal-watchlist-form" onSubmit={event=>{event.preventDefault();add();}}><label htmlFor="watchlist-symbol" className="sr-only">{he?"הוספת נכס":"Add asset"}</label><input id="watchlist-symbol" value={input} onChange={event=>setInput(event.target.value)} placeholder={he?"סימול או שם חברה":"Symbol or company"}/><button className="terminal-control" type="submit">{he?"הוספה":"Add"}</button></form>{note&&<p role="status">{note}</p>}
 {symbols.length?<div className="terminal-table-scroll"><table className="terminal-table"><caption className="sr-only">{he?"רשימת מעקב עם מקור וזמן לכל מחיר":"Watchlist with source and time for every quote"}</caption><thead><tr><th>{he?"נכס":"Asset"}</th><th>{he?"מחיר":"Price"}</th><th>{he?"שינוי":"Change"}</th><th>{he?"מצב ומקור":"Status & source"}</th><th><span className="sr-only">{he?"פעולות":"Actions"}</span></th></tr></thead><tbody>{symbols.map(symbol=>{const asset=assets[symbol];return <tr key={symbol}><td><Link to="/research" state={{symbol}}><bdi>{symbol}</bdi></Link></td><td><bdi className="terminal-number">{asset?`${asset.currency??""} ${asset.price.toLocaleString(undefined,{maximumFractionDigits:2})}`:asset===undefined?"…":"-"}</bdi></td><td><bdi className="terminal-number">{asset?`${asset.changePercent>0?"+":""}${asset.changePercent.toFixed(2)}%`:"-"}</bdi></td><td><StatusIndicator state={asset?asset.freshness==="stale"?"stale":"recent":"unavailable"} label={asset?t(`copilot_freshness_${asset.freshness??"unavailable"}`,asset.freshness??"unavailable"):asset===undefined?(he?"טוען נתוני שוק":"Retrieving market data"):(he?"נתונים לא זמינים":"Data unavailable")}/>{asset&&<small className="terminal-quote-source">{researchCodeLabel("status",asset.marketStatus??"unknown",language)} · {asset.dataSource}{asset.timestamp?` · ${new Date(asset.timestamp).toLocaleString(he?"he-IL":"en-US")}`:""}</small>}</td><td><button className="terminal-control" onClick={()=>setSymbols(current=>current.filter(item=>item!==symbol))} aria-label={`${he?"הסרה":"Remove"} ${symbol}`}>×</button></td></tr>;})}</tbody></table></div>:<p>{he?"רשימת המעקב ריקה. הוסיפו נכס כדי להתחיל.":"Your watchlist is empty. Add an asset to begin."}</p>}<p className="terminal-home-note">{he?"הרשימה נשמרת במכשיר זה בלבד. הנתונים עשויים להיות מעוכבים; מצב, מקור וחותמת זמן מוצגים לכל נכס.":"Watchlist is saved on this device only. Data may be delayed; every asset shows its state, source and timestamp."}</p></Panel>
 <Panel title={he?"תנועות בשוק":"Market movers"}>{movers?<ChatDataDesk data={{kind:"movers",...movers}}/>:<p role="status">{failed?(he?"נתוני שוק אינם זמינים כרגע. אפשר לנסות רענון.":"Market data is unavailable. Try refreshing."):(he?"טוען תנועות בשוק…":"Retrieving market movers…")}</p>}</Panel></div>;
}
