// @vitest-environment jsdom
import {beforeEach,describe,it,expect} from 'vitest';
import {OPERATIONS,OPERATION_EVIDENCE_NUMBERS,REQUIRED_EVIDENCE,chooseOperationEvidence,resolveOperation,OPERATIONS_KEY,OperationsConflictError,closeOperations,correctOperation,decideOperation,isOperationsGame,newOperationsGame,readOperationsGame,readyOperations,restartOperations,saveOperationsGame} from './operationsGame';
beforeEach(()=>localStorage.clear());
describe('merged fictional operations desk',()=>{
 it('keeps packet numbers separate from immutable original breaks',()=>{const fee=OPERATION_EVIDENCE_NUMBERS['F-202']!.map(p=>p.value);expect(fee[0]-fee[1]).toBe(fee[2]);expect(OPERATIONS.find(row=>row.id==='F-202')?.bankCash).toBe(490);expect(OPERATION_EVIDENCE_NUMBERS['S-102']!.map(p=>p.value)).toEqual([4,5]);expect(OPERATIONS.find(row=>row.id==='S-102')?.custodyUnits).toBe(4);});
 it('holds pending fund NAV despite matched units and cash',()=>{const game=decideOperation(newOperationsGame(),'F-201','match');expect(correctOperation(game,'F-201')).toBe(false);expect(correctOperation(decideOperation(game,'F-201','hold'),'F-201')).toBe(true);});
 it('distinguishes unit/cash breaks and duplicate review',()=>{for(const id of ['S-102','F-202'] as const)expect(correctOperation(decideOperation(newOperationsGame(),id,'hold'),id)).toBe(true);expect(correctOperation(decideOperation(newOperationsGame(),'S-103','match'),'S-103')).toBe(false);});
 it('requires every documented fictional control before close and locks closed run',()=>{let game=newOperationsGame();expect(()=>closeOperations(game)).toThrow();for(const row of OPERATIONS){game=decideOperation(game,row.id,row.expected);game=chooseOperationEvidence(game,row.id,REQUIRED_EVIDENCE[row.id]);game=resolveOperation(game,row.id);}expect(readyOperations(game)).toBe(true);game=closeOperations(game);expect(()=>decideOperation(game,'S-101','hold')).toThrow();expect(isOperationsGame(game)).toBe(true);});
 it('persists progress and rejects stale tabs without overwriting',()=>{const game=decideOperation(newOperationsGame(),'S-101','match');saveOperationsGame(game,null);expect(readOperationsGame()).toEqual(game);expect(()=>saveOperationsGame(newOperationsGame(),null)).toThrow(OperationsConflictError);expect(readOperationsGame()).toEqual(game);});
 it('continues only after explicitly loading the latest desk snapshot',()=>{const earlier=decideOperation(newOperationsGame(),'S-101','match');saveOperationsGame(earlier,null);const newer=decideOperation(earlier,'F-201','hold');saveOperationsGame(newer,earlier);expect(()=>saveOperationsGame(earlier,earlier)).toThrow(OperationsConflictError);const latest=readOperationsGame()!;const next=chooseOperationEvidence(latest,'F-201','navApproval');saveOperationsGame(next,latest);expect(readOperationsGame()?.evidence?.['F-201']).toBe('navApproval');expect(readOperationsGame()?.decisions['S-101']).toBe('match');});
 it('archives a closed run without carrying current decisions into the next one',()=>{let game=newOperationsGame();expect(()=>restartOperations(game)).toThrow();for(const row of OPERATIONS){game=decideOperation(game,row.id,row.expected);game=chooseOperationEvidence(game,row.id,REQUIRED_EVIDENCE[row.id]);game=resolveOperation(game,row.id);}const next=restartOperations(closeOperations(game));expect(next.decisions).toEqual({});expect(next.checked).toEqual([]);expect(next.closed).toBe(false);expect(next.runs?.[0].metrics).toEqual({resolved:7});expect(isOperationsGame(next)).toBe(true);});
 it('does not resolve exceptions using market prices or unapproved book edits',()=>{let game=decideOperation(newOperationsGame(),'S-102','hold');game=chooseOperationEvidence(game,'S-102','marketQuote');expect(()=>resolveOperation(game,'S-102')).toThrow();game=chooseOperationEvidence(game,'S-102','manualEdit');expect(()=>resolveOperation(game,'S-102')).toThrow();game=chooseOperationEvidence(game,'S-102','position');expect(resolveOperation(game,'S-102').resolved).toContain('S-102');});
 it('classification is not enough for new cases, and changing it invalidates evidence',()=>{let game=newOperationsGame();for(const row of OPERATIONS)game=decideOperation(game,row.id,row.expected);expect(readyOperations(game)).toBe(false);expect(()=>closeOperations(game)).toThrow();game=chooseOperationEvidence(game,'S-102','position');game=resolveOperation(game,'S-102');game=decideOperation(game,'S-102','match');expect(game.evidence?.['S-102']).toBeUndefined();expect(game.resolved).not.toContain('S-102');});
 it('rejects fabricated resolution and wrong evidence packets',()=>{const game=decideOperation(newOperationsGame(),'F-201','hold');expect(isOperationsGame({...game,resolved:['F-201'],evidence:{'F-201':'marketQuote'}})).toBe(false);expect(isOperationsGame({...game,resolved:['unknown']})).toBe(false);expect(()=>chooseOperationEvidence(game,'S-101','books')).toThrow();});
 it('keeps legacy classifications readable without silently reopening a completed run',()=>{const game={decisions:Object.fromEntries(OPERATIONS.slice(0,6).map(row=>[row.id,row.expected])),checked:OPERATIONS.slice(0,6).map(row=>row.id),closed:true};expect(isOperationsGame(game)).toBe(true);expect(restartOperations(game).evidence).toEqual({});});
 it('rejects corrupt and falsely completed storage',()=>{localStorage.setItem(OPERATIONS_KEY,'bad');expect(readOperationsGame()).toBeNull();expect(isOperationsGame({...newOperationsGame(),closed:true})).toBe(false);expect(isOperationsGame({...newOperationsGame(),decisions:{oops:'match'}})).toBe(false);});
});

it('keeps original six-record closed and in-progress runs valid after expansion',()=>{
 const original=OPERATIONS.slice(0,6);const legacy={decisions:Object.fromEntries(original.map(row=>[row.id,row.expected])),checked:original.map(row=>row.id),closed:true};
 expect(isOperationsGame(legacy)).toBe(true);localStorage.setItem(OPERATIONS_KEY,JSON.stringify(legacy));expect(readOperationsGame()).toEqual(legacy);expect(restartOperations(legacy).caseVersion).toBe(2);expect(restartOperations(legacy).runs?.[0].metrics.resolved).toBe(6);
 const inProgress={...legacy,closed:false,evidence:{},resolved:[]};expect(isOperationsGame(inProgress)).toBe(true);expect(readyOperations(inProgress)).toBe(false);
});
it('requires a packet supporting both position and cash in the combined break',()=>{
 let game=decideOperation(newOperationsGame(),'S-104','hold');for(const evidence of ['position','cashExplanation','books','marketQuote','manualEdit'] as const){game=chooseOperationEvidence(game,'S-104',evidence);expect(()=>resolveOperation(game,'S-104')).toThrow();}
 game=chooseOperationEvidence(game,'S-104','combinedApproval');expect(resolveOperation(game,'S-104').resolved).toContain('S-104');
 const values=Object.fromEntries(OPERATION_EVIDENCE_NUMBERS['S-104']!.map(p=>[p.label,p.value]));expect(values.grossCash-values.documentedFee).toBe(values.netBankCash);expect(values.supportedCustodyUnits-values.originalCustodyUnits).toBe(1);
});

it('does not introduce the new record into an older saved exercise',()=>{
 const old={decisions:{},checked:[],closed:false,evidence:{},resolved:[]};expect(()=>decideOperation(old,'S-104','hold')).toThrow();expect(isOperationsGame({...old,decisions:{'S-104':'hold'},checked:['S-104']})).toBe(false);
 let game:import('./operationsGame').OperationsGame=old;for(const row of OPERATIONS.slice(0,6)){game=decideOperation(game,row.id,row.expected);game=chooseOperationEvidence(game,row.id,REQUIRED_EVIDENCE[row.id]);game=resolveOperation(game,row.id);}
 expect(isOperationsGame(closeOperations(game))).toBe(true);expect(restartOperations(closeOperations(game)).runs?.[0].metrics.resolved).toBe(6);
});

it('cannot bypass expanded evidence requirements by removing fields or supplying a false version',()=>{expect(isOperationsGame({...newOperationsGame(),evidence:undefined})).toBe(false);expect(isOperationsGame({...newOperationsGame(),resolved:undefined})).toBe(false);expect(isOperationsGame({...newOperationsGame(),caseVersion:999})).toBe(false);});
