import {PracticeHistory} from '@/components/career/PracticeHistory';
import {useEffect,useId,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {Layout,DisclaimerBanner} from '@/components/layout/Layout';
import {SourceMarketPanel} from '@/components/career/SourceMarketPanel';
import {useLanguage} from '@/context/languageContext';
import {operationCases,OPERATION_EVIDENCE_NUMBERS,REQUIRED_EVIDENCE,chooseOperationEvidence,resolveOperation,resolvedOperation,OperationsConflictError,closeOperations,correctOperation,decideOperation,newOperationsGame,readOperationsGame,readyOperations,restartOperations,saveOperationsGame,type OperationEvidence,type OperationDecision,type OperationsGame} from '@/lib/career/operationsGame';
export default function OperationsGamePage(){
 const {t,language}=useLanguage();const saved=useRef<OperationsGame|null>(readOperationsGame());const [game,setGame]=useState(()=>saved.current??newOperationsGame());const [index,setIndex]=useState(0);const [error,setError]=useState('');const [conflicted,setConflicted]=useState(false);
 const inspectId=useId();const heading=useRef<HTMLHeadingElement>(null);const resolution=useRef<HTMLParagraphElement>(null);const closure=useRef<HTMLParagraphElement>(null);const pendingFocus=useRef<'resolution'|'inspect'|'closed'|null>(null);
 useEffect(()=>{if(pendingFocus.current==='resolution')resolution.current?.focus();if(pendingFocus.current==='closed')closure.current?.focus();if(pendingFocus.current==='inspect')heading.current?.focus();pendingFocus.current=null;},[game]);
 const rows=operationCases(game);const row=rows[Math.min(index,rows.length-1)];const count=rows.filter(item=>resolvedOperation(game,item.id)).length;
 function persist(next:OperationsGame){try{saveOperationsGame(next,saved.current);saved.current=next;setGame(next);setError('');setConflicted(false);}catch(cause){pendingFocus.current=null;setConflicted(cause instanceof OperationsConflictError);setError(t(cause instanceof OperationsConflictError?'ops_conflict':'ops_save_error'));}}
 function loadLatest(){pendingFocus.current='inspect';const latest=readOperationsGame();saved.current=latest;const next=latest??newOperationsGame();setGame(next);setIndex(current=>Math.min(current,operationCases(next).length-1));setError('');setConflicted(false);}
 return <Layout><section className="container max-w-[1400px] py-8" dir={language==='he'?'rtl':'ltr'}><div className="career-desk rounded-xl border border-teal-900 bg-[#0b1220] p-5 text-slate-100 space-y-5 [&_h1]:!text-slate-100 [&_h2]:!text-slate-100 [&_h3]:!text-slate-100 [&_p]:!text-slate-100 [&_input]:!text-slate-100 [&_input]:!bg-[#111d30]">
 <div className="flex flex-wrap justify-between gap-2 border-b border-teal-500/30 pb-3 text-xs font-mono text-teal-200"><span dir="ltr">OPERATIONS DESK · SECURITIES / FUNDS</span><b>{t('game_ticker_fake')}</b></div><Link to="/career-lab" className="text-sm text-teal-300 underline">{t('game_back')}</Link><h1 className="text-2xl font-bold">{t('ops_title')}</h1><p className="rounded-lg border border-amber-400/40 bg-amber-400/10 p-4 text-sm">{t('ops_disclaimer')}</p>
 <SourceMarketPanel/>
 <PracticeHistory runs={game.runs}/>
 <div className="grid gap-3 sm:grid-cols-3">{[['ops_total',rows.length],['ops_resolved',count],['ops_remaining',rows.length-count]].map(([key,value])=><div key={key} className="rounded border border-slate-700 bg-[#111d30] p-4"><p className="text-xs">{t(String(key))}</p><b dir="ltr" className="text-xl">{value}</b></div>)}</div>
 <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.5fr)]"><section className="min-w-0 rounded-xl border border-slate-700 bg-[#111d30] p-4 space-y-3"><h2 className="text-xl font-semibold">{t('ops_queue')}</h2><p className="text-xs">{t('ops_queue_note')}</p><a href={`#${inspectId}`} className="inline-block rounded border border-teal-300 px-3 py-2 text-sm !text-teal-200" onClick={()=>heading.current?.focus()}>{t('ops_go_inspect')}</a><div role="group" aria-label={t('ops_queue')} className="space-y-2">{rows.map((item,i)=><button key={item.id} type="button" aria-controls={inspectId} aria-pressed={index===i} onClick={()=>setIndex(i)} className={`w-full rounded-lg border p-3 text-start ${index===i?'border-teal-300 bg-teal-300/10':'border-slate-600'}`}><div className="flex flex-wrap justify-between gap-2"><b dir="ltr" className="font-mono">{item.id} · {item.symbol}</b><span className="text-xs">{t(`ops_kind_${item.kind}`)}</span></div><p className="mt-1 text-xs">{t(resolvedOperation(game,item.id)?'ops_resolved_record':correctOperation(game,item.id)?'ops_await_evidence':game.checked.includes(item.id)?'ops_review':'ops_unreviewed')}</p></button>)}</div></section>
 <section className="min-w-0 rounded-xl border border-slate-700 bg-[#111d30] p-4 space-y-4"><div className="flex flex-wrap justify-between gap-2"><h2 id={inspectId} ref={heading} tabIndex={-1} className="text-xl font-semibold">{t('ops_inspect')} · <span dir="ltr">{row.id}</span></h2></div><p className="text-sm">{t('ops_instruction')}</p><p className="text-xs text-slate-300">{t('ops_glossary')}</p><table className="w-full table-fixed text-xs sm:text-sm"><caption className="text-start mb-3 text-xs">{t('ops_records_note')}</caption><thead><tr><th scope="col" className="p-2 text-start">{t('ops_field')}</th><th scope="col" className="p-2 text-end">{t('ops_internal')}</th><th scope="col" className="p-2 text-end">{t('ops_external')}</th></tr></thead><tbody>{[['ops_units',row.units,row.custodyUnits],['ops_cash',row.cash,row.bankCash]].map(([key,a,b])=><tr key={key} className="border-t border-slate-700"><th scope="row" className="p-2 text-start">{t(String(key))}</th><td dir="ltr" className="p-2 text-end font-mono">{a}</td><td dir="ltr" className={`p-2 text-end font-mono ${a!==b?'text-amber-200':''}`}>{b}</td></tr>)}</tbody></table><dl className="grid gap-3 sm:grid-cols-2"><div className="rounded border border-slate-600 p-3"><dt className="text-xs">{t('ops_reference')}</dt><dd dir="ltr" className="font-mono">{row.reference}</dd><dd className="mt-1 text-xs">{t(row.duplicate?'ops_duplicate':'ops_unique')}</dd></div><div className="rounded border border-slate-600 p-3"><dt className="text-xs">{t('ops_nav')}</dt><dd className="mt-1 text-sm">{t(`ops_nav_${row.nav}`)}</dd></div></dl>
 <div className="rounded border border-sky-400/40 bg-[#07101f] p-3"><h3 className="font-semibold">{t('ops_control_title')}</h3><p className="mt-2 text-sm">{t('ops_controls')}</p></div><div role="group" aria-label={t('ops_instruction')} className="flex flex-wrap gap-2">{(['match','hold','escalate'] as OperationDecision[]).map(decision=><button key={decision} type="button" disabled={game.closed} aria-pressed={game.decisions[row.id]===decision} onClick={()=>persist(decideOperation(game,row.id,decision))} className={`rounded-lg border px-4 py-3 text-sm ${game.decisions[row.id]===decision?'border-teal-300 bg-teal-300/10':'border-slate-500'} disabled:opacity-50`}>{t(`ops_decision_${decision}`)}</button>)}</div>
 {game.checked.includes(row.id)&&<p role="status" className="rounded border border-slate-600 p-3 text-sm">{t(correctOperation(game,row.id)?'ops_correct':'ops_retry')} {t(`ops_reason_${row.reason}`)}</p>}
 {game.evidence!==undefined&&correctOperation(game,row.id)&&<section className="rounded-xl border border-teal-500/40 bg-[#07101f] p-4 space-y-3" aria-label={t('ops_evidence_title')}><h3 className="font-semibold">{t('ops_evidence_title')}</h3><p className="text-sm">{t('ops_evidence_instruction')}</p><div role="group" aria-label={t('ops_evidence_title')} className="grid gap-2 sm:grid-cols-2">{([REQUIRED_EVIDENCE[row.id],'marketQuote','manualEdit'] as OperationEvidence[]).map(evidence=><button key={evidence} type="button" disabled={game.closed} aria-pressed={game.evidence?.[row.id]===evidence} onClick={()=>persist(chooseOperationEvidence(game,row.id,evidence))} className={`rounded-lg border p-3 text-start text-sm ${game.evidence?.[row.id]===evidence?'border-teal-300 bg-teal-300/10':'border-slate-600'} disabled:opacity-90`}>{t(`ops_evidence_${evidence}`)}</button>)}</div>{game.evidence[row.id]&&<p role="status" className="text-sm">{t(game.evidence[row.id]===REQUIRED_EVIDENCE[row.id]?`ops_support_${row.reason}`:'ops_evidence_rejected')}</p>}{game.evidence[row.id]===REQUIRED_EVIDENCE[row.id]&&OPERATION_EVIDENCE_NUMBERS[row.id]&&<dl aria-label={t('ops_packet_numbers')} className="grid grid-cols-2 gap-2">{OPERATION_EVIDENCE_NUMBERS[row.id]!.map(point=><div key={point.label} className="min-w-0 rounded border border-slate-600 bg-[#111d30] p-2"><dt className="text-xs">{t(`ops_packet_${point.label}`)}</dt><dd dir="ltr" className="mt-1 font-mono text-teal-200">{point.value}</dd></div>)}</dl>}{resolvedOperation(game,row.id)?<p ref={resolution} tabIndex={-1} role="status" aria-atomic="true" className="text-sm text-teal-200">{t(`ops_resolution_${row.reason}`)}</p>:<button type="button" disabled={game.closed||game.evidence[row.id]!==REQUIRED_EVIDENCE[row.id]} className="rounded-lg border border-teal-300 p-3 text-sm disabled:opacity-40" onClick={()=>{pendingFocus.current='resolution';persist(resolveOperation(game,row.id));}}>{t('ops_resolve')}</button>}<p className="text-xs text-slate-300">{t('ops_resolution_note')}</p></section>}
 {game.closed?<p ref={closure} tabIndex={-1} role="status" className="rounded border border-teal-300 p-3 text-sm">{t(game.evidence===undefined?'ops_legacy_closed':'ops_closed')}</p>:<button type="button" disabled={!readyOperations(game)} onClick={()=>{pendingFocus.current='closed';persist(closeOperations(game));}} className="rounded-lg bg-teal-400 px-4 py-3 font-semibold text-[#07101f] disabled:opacity-40">{t('ops_close')}</button>}
 {game.closed&&<button type="button" className="rounded-lg border border-teal-300 p-3 text-sm" onClick={()=>{if(window.confirm(t('practice_restart_confirm'))){pendingFocus.current='inspect';persist(restartOperations(game));setIndex(0);}}}>{t('practice_restart')}</button>}
 </section></div>{error&&<div className="space-y-2"><p role="alert" className="text-rose-300">{error}</p>{conflicted&&<button type="button" className="rounded-lg border border-teal-300 p-3 text-sm" onClick={loadLatest}>{t('ops_load_latest')}</button>}</div>}
 </div><DisclaimerBanner/></section></Layout>;
}
