import {useState} from 'react';
import {useLanguage} from '@/context/languageContext';
import {CLIENT_PROFILES,GAME_DAYS,clientMessage,clientReply,portfolioClients,type ClientId,type GameAction,type PortfolioGame} from '@/lib/career/portfolioGame';

/** Device-local staged conversations. No email integration or real recipients. */
export function ClientInbox({game,onAction}:{game:PortfolioGame;onAction:(action:GameAction)=>void}){
  const {t}=useLanguage();
  const [selected,setSelected]=useState<ClientId>('cautious');
  const client=portfolioClients(game).find(client=>client.id===selected)!;
  const message=clientMessage(game,selected);
  const plan=game.clientPlans?.[selected]?.[game.day]??'none';
  const reply=clientReply(game,selected,game.day);
  return <section className="rounded-xl border border-slate-700 bg-[#111d30] p-4 space-y-3" aria-label={t('game_personal_inbox')}><h2 className="text-xl font-semibold">{t('game_personal_inbox')}</h2><p className="text-xs font-mono text-amber-200">{t('game_staged_sender')}</p><div className="flex flex-wrap gap-2" aria-label={t('game_select_client')}>{CLIENT_PROFILES.map(profile=><button key={profile.id} type="button" aria-pressed={selected===profile.id} className={`rounded-lg border px-3 py-2 text-xs ${selected===profile.id?'border-teal-300 bg-teal-300/10':'border-slate-600'}`} onClick={()=>setSelected(profile.id)}>{t(`game_client_name_${profile.id}`)}</button>)}</div><div className="rounded-lg border border-slate-600 bg-[#07101f] p-3 space-y-2"><h3 className="font-semibold">{t(`game_client_${selected}`)}</h3><p className="text-xs">{t('game_day')} {game.day+1} · {t('game_trust')} <span dir="ltr">{client.trust}/100</span></p><p className="text-sm">{t(`game_personal_${selected}_${message.topic}`)}</p>{message.topic==='loss'&&<p className="text-xs">{t('game_personal_loss')}: <span dir="ltr">{message.loss}%</span></p>}</div><p className="text-xs">{t('game_personal_reply_note')}</p>{client.active&&!game.settled&&reply==='none'?<div className="flex flex-wrap gap-2">{(['explained','guaranteed','ignored'] as const).map(answer=><button type="button" key={answer} className="rounded-lg border border-slate-500 p-2 text-sm" onClick={()=>onAction({type:'reply',clientId:selected,answer})}>{t(answer==='explained'?'game_reply':answer==='guaranteed'?'game_guarantee':'game_ignore')}</button>)}</div>:<p role="status" className="text-sm">{t(!client.active?'game_personal_closed':`game_answer_${reply}`)}</p>}<fieldset className="rounded-lg border border-slate-600 p-3 space-y-2"><legend className="px-1 text-sm font-semibold">{t('game_client_plan')}</legend><p className="text-xs">{t(game.planVersion===2?'game_client_plan_note':'game_client_plan_note_v1')}</p>{client.active&&!game.settled&&plan==='none'?<div className="flex flex-wrap gap-2">{(['cashBuffer','monitor'] as const).map(choice=><button type="button" key={choice} className="rounded border border-teal-500/50 p-2 text-xs" onClick={()=>onAction({type:'plan',clientId:selected,plan:choice})}>{t(`game_plan_${choice}`)}</button>)}</div>:<p className="text-xs">{t(`game_plan_${plan}`)}</p>}</fieldset><details className="rounded-lg border border-slate-700 p-3"><summary className="cursor-pointer text-sm">{t('game_personal_history')}</summary><ol className="mt-3 space-y-2">{GAME_DAYS.slice(0,game.day+1).map((day,index)=><li key={index} className="border-b border-slate-700 pb-2 text-xs"><b>{t('game_day')} {index+1}</b><p>{t(`game_mail_${day.client}`)}</p><p>{t(`game_answer_${clientReply(game,selected,index)}`)}</p></li>)}</ol></details><p className="text-xs">{t('game_mail_note')}</p></section>;
}
