import {useId,useRef,useState} from 'react';
import {useLanguage} from '@/context/languageContext';
import {COMMITTEE_CASES,COMMITTEE_NUMBERS,CommitteeConflictError,readCommitteeState,saveCommitteeState,type CommitteeRole,type CommitteeDecision,type CommitteeCaseState} from '@/lib/career/committeeCases';
/** Optional local practice. No change to the main game's fictional company or ledger. */
export function CommitteeCases({role}:{role:CommitteeRole}){
 const panelId=useId();const selectedButton=useRef<HTMLButtonElement>(null);const {t}=useLanguage();const saved=useRef(readCommitteeState(role));const [state,setState]=useState<CommitteeCaseState>(()=>saved.current??{decisions:{}});const [error,setError]=useState('');const [conflicted,setConflicted]=useState(false);const [selected,setSelected]=useState<string>(COMMITTEE_CASES[role][0].id);
 function choose(id:string,decision:CommitteeDecision){const next={decisions:{...state.decisions,[id]:decision}};try{saveCommitteeState(role,next,saved.current);saved.current=next;setState(next);setError('');setConflicted(false);}catch(cause){setConflicted(cause instanceof CommitteeConflictError);setError(t(cause instanceof CommitteeConflictError?'committee_conflict':'committee_save_error'));}}
 function loadLatest(){const latest=readCommitteeState(role);saved.current=latest;setState(latest??{decisions:{}});setError('');setConflicted(false);selectedButton.current?.focus();}
 return <details className="rounded-xl border border-slate-700 bg-[#111d30] p-4"><summary className="cursor-pointer font-semibold">{t('committee_title')} · {t(`committee_role_${role}`)} · {COMMITTEE_CASES[role].filter(row=>state.decisions[row.id]===row.correct).length}/{COMMITTEE_CASES[role].length}</summary><p className="mt-3 text-xs">{t('committee_note')}</p><div role="group" className="mt-4 flex flex-wrap gap-2" aria-label={t('committee_select_case')}>{COMMITTEE_CASES[role].map((row,index)=><button key={row.id} type="button" ref={selected===row.id?selectedButton:undefined} aria-controls={panelId} aria-pressed={selected===row.id} onClick={()=>setSelected(row.id)} className={`rounded-lg border px-3 py-2 text-sm ${selected===row.id?'border-teal-300 bg-teal-300/10':'border-slate-500'}`}>{index+1}. {t(`committee_case_${row.id}`)}{state.decisions[row.id]===row.correct?' ✓':''}</button>)}</div><div id={panelId} className="mt-4">{COMMITTEE_CASES[role].filter(row=>row.id===selected).map(row=><section key={row.id} className="rounded-lg border border-slate-600 bg-[#07101f] p-4 space-y-3"><h3 className="font-semibold">{t(`committee_case_${row.id}`)}</h3><p className="text-sm">{t(`committee_facts_${row.facts}`)}</p><dl className="grid grid-cols-2 gap-2">{COMMITTEE_NUMBERS[row.id].map(point=><div key={point.label} className="min-w-0 rounded border border-slate-700 bg-[#111d30] p-2"><dt className="text-xs">{t(`committee_number_${point.label}`)}</dt><dd dir="ltr" className={`mt-1 font-mono text-sm ${point.value<0?'text-rose-200':'text-teal-200'}`}>{point.value} {t(`committee_unit_${point.unit}`)}</dd></div>)}</dl><p className="text-xs text-slate-300">{t('committee_numbers_note')}</p><div role="group" aria-label={t('committee_decision')} className="flex flex-wrap gap-2">{(['approve','review','defer'] as const).map(decision=><button key={decision} type="button" aria-pressed={state.decisions[row.id]===decision} className={`rounded-lg border px-3 py-2 text-sm ${state.decisions[row.id]===decision?'border-teal-300 bg-teal-300/10':'border-slate-500'}`} onClick={()=>choose(row.id,decision)}>{t(`committee_${decision}`)}</button>)}</div>{state.decisions[row.id]&&<p role="status" aria-atomic="true" className="text-sm">{t(state.decisions[row.id]===row.correct?'committee_correct':'committee_retry')} {t(`committee_reason_${row.reason}`)}</p>}</section>)}</div>{error&&<div className="mt-3 space-y-2"><p role="alert" className="text-sm text-rose-300">{error}</p>{conflicted&&<button type="button" className="rounded-lg border border-teal-300 px-3 py-2 text-sm" onClick={loadLatest}>{t('committee_load_latest')}</button>}</div>}</details>;
}
